### PR TITLE
Updated Aerospike class

### PR DESCRIPTION
**Pull request by sergeyklay**
Hi!

Also I don't quite understand the method [Aerospike::getHeader][1]
Can you please explain a bit more?
Thanks

[1]: https://github.com/aerospike/aerospike-client-php/blob/master/src/aerospike/aerospike.c#L1512

### CODE REVIEW

**Comment by rbotzer** [comment]
Thanks for the cleanup. I'll grab this before the next release. getHeader() is deprecated, so please ignore it. In other language APIs there may be a distinction between getHeader() which returns the record metadata, (like the PHP client's exists()), and just checking for existence (returning a boolean).

**Comment by sergeyklay** [comment]
Also I managed to grab a [lot more  of constants](https://github.com/sergeyklay/aerospike-php-stubs/blob/master/src/Aerospike.php) :)

**Comment by rbotzer** [comment]
:trophy:

**Comment by sergeyklay** [comment]
What with this PR?

**Comment by rbotzer** [comment]
Will be pulled into our private repo, then rolled out with the next release. Thanks.

**Comment by sergeyklay** [comment]
:+1:

**Comment by rbotzer** [comment]
Pulled, will get pushed out with release 3.4.6.

**Comment by sergeyklay** [comment]
:+1:

**Pull request closed without merging**
